INSERT INTO DimCompany (SK_CompanyID,CompanyID, Status,Name,Industry,SPrating,isLowGrade,CEO,AddressLine1,AddressLine2,PostalCode,City,StateProv,Country,Description,FoundingDate,IsCurrent,BatchID,EffectiveDate,EndDate)
SELECT C.CIK, C.CIK, S.ST_NAME, C.COMPANY_NAME, I.IN_NAME,C.SP_RATING, 
    CASE 
        WHEN LPAD(C.SP_RATING,1)='A' OR LPAD(C.SP_RATING,3)='BBB' THEN
            'false'
        ELSE
            'true'
        END,
    C.CEO_NAME, C.ADDR_LINE_1,C.ADDR_LINE_2, C.POSTAL_CODE, C.CITY, C.STATE_PROVINCE, C.COUNTRY, C.DESCRIPTION,
    TO_DATE(FOUNDING_DATE,'YYYYMMDD'),'true', 1, TO_DATE(LPAD(C.PTS,8),'YYYYMMDD'), TO_DATE('99991231','YYYYMMDD')
FROM S_Company C
JOIN Industry I ON C.INDUSTRY_ID = I.IN_ID
JOIN StatusType S ON C.STATUS = S.ST_ID;

CREATE TABLE sdc_dimcompany 
   (	"SK_COMPANYID" NUMBER(11,0), 
	"COMPANYID" NUMBER(11,0) NOT NULL ENABLE, 
	"STATUS" CHAR(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"NAME" CHAR(60) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INDUSTRY" CHAR(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"SPRATING" CHAR(4) COLLATE "USING_NLS_COMP", 
	"ISLOWGRADE" CHAR(5) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CEO" CHAR(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ADDRESSLINE1" CHAR(80) COLLATE "USING_NLS_COMP", 
	"ADDRESSLINE2" CHAR(80) COLLATE "USING_NLS_COMP", 
	"POSTALCODE" CHAR(12) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CITY" CHAR(25) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STATEPROV" CHAR(20) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COUNTRY" CHAR(24) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" CHAR(150) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FOUNDINGDATE" DATE, 
	"ISCURRENT" CHAR(5) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BATCHID" NUMBER(5,0) NOT NULL ENABLE, 
	"EFFECTIVEDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE NOT NULL ENABLE, 
	 CHECK (isLowGrade = 'true' OR isLowGrade = 'false') ENABLE, 
	 CHECK (IsCurrent = 'true' OR IsCurrent = 'false') ENABLE, 
	 PRIMARY KEY ("SK_COMPANYID"));

ALTER TABLE sdc_dimcompany
    ADD RN DECIMAL;

INSERT INTO sdc_dimcompany
SELECT DC.*, ROW_NUMBER() OVER(ORDER BY CompanyID, EffectiveDate) RN
FROM DimCompany DC;

UPDATE DimCompany 
SET DimCompany.EndDate = 
    (SELECT EndDate FROM ( 
        SELECT s1.SK_CompanyID,
                s2.EffectiveDate EndDate
        FROM sdc_dimcompany s1
        JOIN sdc_dimcompany s2 ON (s1.RN = (s2.RN - 1) AND s1.CompanyID = s2.CompanyID)
        WHERE s1.CompanyID = DimCompany.CompanyID)),
    DimCompany.IsCurrent='false';

DROP TABLE sdc_dimcompany;