LOAD DATA 
INTO TABLE S_Daily_Market 
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
    DM_DATE DATE "YYYY-MM-DD",
    DM_S_SYMB,
    DM_CLOSE,
    DM_HIGH,
    DM_LOW,
    DM_VOL
)